### ISSUE TITLE
Missing option to track reload status

### ISSUE THREAD

**Issue by sakchhams** [chimon2000/async_loader#11]
### The current implementation allows for reload using 
- `reloadState() {
    _initState();
  }
`
- `initState` returns a `Future` and hence can be used to get notified when operation has finished. 
- `reloadState` however is not 'async' and does not return anything.

### Problem
- When using something like a `RefreshIndicator` you need a callback when the refresh process has finished so that the progress indicator can be removed.

**Comment by chimon2000** [comment]
@sakchhams in the latest version `reloadState` will return a promise that you can resolve using `whenComplete`.  Please confirm that this resolves your problem and if so, close this issue.
