### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by castrors** [chimon2000/async_loader#5]
Hi there,

Let me explain my project:
I'm trying to develop an "Master-Detail" app using async_loader lib. The app consumes Github api listing some repositories. After that, if a user click on an list item he is sent to detail screen that consumes github api again to show the pull requests of that repository.

When i click to see the detail screen, I got that message of error:
```
setState() called after dispose(): AsyncLoaderState#dbc13(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
breaking at exception: FlutterError
```

Here is my project in case you want to run and see what is happening:
[GithubFlutter](https://github.com/castrors/GithubFlutter)

**Comment by chimon2000** [comment]
@castrors Thanks for discovering this issue.  Please verify that this has been resolved in the latest release v0.1.1
